spring.application.name=demo
spring.datasource.url=jdbc:h2:mem:investimentosdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.output.ansi.enabled=ALWAYS
# console.logging.pattern=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15thread]){blue} %clr(%-40.40logger{39}){cyan} %clr([x-fapi-tracing){magenta}=%clr(%X{x-fapi-interaction-id:-n/a}){green}%clr(]){magenta} %clr(-){faint} %msg%n%wEx